### ISSUE TITLE
Large gap beneath book title while reading pages

### ISSUE THREAD

**Issue by Munchotaur** [taylorskalyo/goreader#4]
Goreader seems to allow 12-13 lines below the book title at the start of each page or chapter. Is there any way to reduce this? On terminals with large text that makes for a lot of empty space and only a few lines of text at the bottom...

**Comment by taylorskalyo** [comment]
_I apologize for not responding sooner!_ I must not have had notifications set up properly...

I think what's happening here is that newlines in the underlying html within the epub file are all getting printed to the terminal. This is because goreader currently doesn't attempt to handle whitespace correctly. A real web engine would not print newline characters as actual new lines and would [collapse the whitespace](https://www.w3.org/TR/CSS21/text.html#white-space-model).

Eventually I think it would be neat to implement whitespace handling the way a web browser would, as well as proper box layout, tables, and CSS parsing, maybe using [robinson](https://github.com/mbrubeck/robinson) as a starting point (though currently it doesn't handle inline blocks or text painting, which are some of the most important pieces for a project like this).

In the meantime, I just created a [whitespace branch](https://github.com/taylorskalyo/goreader/tree/whitespace) that I think might fix the issue you're seeing (see the before and after screenshot below). I know it's been a while since you opened the issue, but if you're still using goreader and the changes in the whitespace branch don't resolve the issue, definitely let me know, and I'll dig a little deeper.

![untitled](https://user-images.githubusercontent.com/2508427/46593378-7e259780-ca99-11e8-8b9e-21859e0dbeac.png)

**Comment by Munchotaur** [comment]
No problem about the reply lag! It's great to see a maintained console epub reader.

Am I right in thinking I can't check out a branch using 'go get'? Should I uninstall that version then clone the branch instead directly from git prior to building manually?

**Comment by taylorskalyo** [comment]
Correct, as far as I know you can't `go get` a specific branch. But you should be able to do something like:

```
cd $GOPATH/src/github.com/taylorskalyo/goreader
git fetch
git checkout whitespace
go install
```

I expect manually cloning and building would also work if you'd rather go that route.

**Comment by taylorskalyo** [comment]
@Munchotaur Were you able to get the whitespace branch working? I'm considering merging in these changes, but I'm curious to see if you have any feedback before I do.

**Comment by Munchotaur** [comment]
Sorry, haven't had the chance to test as very busy the last couple of weeks. I'll give it a look soon...

**Comment by Munchotaur** [comment]
I've just taken a look and the header spacing works really well.

I took a screenshot to demonstrate this, and noticed that small caps seem to cause some spacing issues. I took a look inside the epub and the small caps were implemented with styled span elements around the first letter of the word. The small caps style increases the line height and changes the font size a little.

![goreader-smallcaps-spacing](https://user-images.githubusercontent.com/9674847/48491934-9323e200-e820-11e8-8794-d37eba16a40e.png)

**Comment by taylorskalyo** [comment]
I appreciate your help with testing! I'm going to go ahead and merge in the whitespace branch, since that seems to fix the issues with vertical spacing.

To fix the horizontal spacing, I'll need to implement whitespace collapsing between elements.

**Comment by taylorskalyo** [comment]
Okay, I think I've got a solution for collapsing whitespace between elements. If you're interested in trying it out, the changes are in the `collapse_whitespace` branch.

**Comment by Munchotaur** [comment]
That works!

**Comment by taylorskalyo** [comment]
Wonderful! I'll merge in those changes then, and mark this issue closed.
